name: Liskaphoto
favicon: null
layout_spectrum: 0.24939
typography_spectrum: 0.19515
title: 'photo video & design'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e6d1b9'
    - '#6985ae'
    - '#da222d'
    - '#ff656e'
    - '#281a10'
  brandStrength: 0.0625
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
