name: Liskaphoto
favicon: null
layout_spectrum: 0.24939
typography_spectrum: 0.10273593431338668
title: 'photo video & design'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.1875
  lightness: 0.3431170948315412
  saturation: 0.6997282854281366
  rhythmicContrast: 0.12107735243625939
purpose: []
